_wandb:
    value:
        cli_version: 0.21.0
        e:
            q3ljvc45a1sh0c2otn7ovv94ewwfc033:
                codePath: train.py
                codePathLocal: train.py
                cpu_count: 8
                cpu_count_logical: 16
                cudaVersion: "12.8"
                disk:
                    /:
                        total: "214748360704"
                        used: "191269720064"
                email: UnlivedDisc03@gmail.com
                executable: C:\Users\Unliv\PycharmProjects\IndividualProjectRedone\.venv\Scripts\python.exe
                git:
                    commit: 2d796350657abac6eb7562f4c3b3d24a8d5c7693
                    remote: https://github.com/UnlivedDisc03/final-project-actual
                gpu: NVIDIA GeForce GTX 1650 Ti
                gpu_count: 1
                gpu_nvidia:
                    - architecture: Turing
                      cudaCores: 1024
                      memoryTotal: "4294967296"
                      name: NVIDIA GeForce GTX 1650 Ti
                      uuid: GPU-995cbeaf-e18e-6bd3-44db-08596f0ce625
                host: DESKTOP-JBEA1UO
                memory:
                    total: "33685716992"
                os: Windows-10-10.0.19045-SP0
                program: C:\Users\Unliv\PycharmProjects\IndividualProjectRedone\train.py
                python: CPython 3.12.8
                root: C:\Users\Unliv\PycharmProjects\IndividualProjectRedone
                startedAt: "2025-07-11T13:44:54.601440Z"
                writerId: q3ljvc45a1sh0c2otn7ovv94ewwfc033
        m: []
        python_version: 3.12.8
        t:
            "1":
                - 1
                - 41
            "2":
                - 1
                - 41
            "3":
                - 13
                - 16
            "4": 3.12.8
            "5": 0.21.0
            "8":
                - 3
            "12": 0.21.0
            "13": windows-amd64
train:
    value:
        agg_func: median
        epochs: 3
        image_size: 640
        train_tomato: false
        weighted_dataset: true
        yolo: 8
